export const actionTypes = {
    SET_USERNAME: 'SET_USERNAME',
    SET_PASSWORD: 'SET_PASSWORD', 
    SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_FAILURE: 'LOGIN_REQUEST_FAILURE',  
    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
}